export const CONS_SETTING_LANGUAGE_DIRECTION_LTR = "LTR";
export const CONS_SETTING_LANGUAGE_DIRECTION_RTL = "RTL";

export const CONS_PREMIUM_TYPE_MONTHLY = "Monthly";
export const CONS_PREMIUM_TYPE_YEARLY = "Yearly";
export const CONS_PREMIUM_TYPE_LIFETIME = "Lifetime";
